src/comps/Header.tsx

Add testnet banner

---

src/app/api/bitcoind/route.ts
src/app/api/proxy/[...proxy]/route.ts
src/app/layout.tsx
src/util/atoms.ts
src/util/bitcoinClient.ts

bug - resolve build issues with nextjs

---

src/app/api/proxy/[...proxy]/route.ts
src/comps/Deposit.tsx
src/comps/alerts/info.tsx
src/comps/alerts/success.tsx
src/hooks/use-deposit-status.ts
src/util/tx-utils.ts

As a user I want to see the status of my deposit after I send the btc deposit transaction
Closes https://github.com/stacks-network/sbtc/issues/938

add deposit status tracking ui after deposit is sent

---

.eslintrc.json
package.json
src/actions/get-testnet-btc.ts
src/comps/Header.tsx
src/comps/get-testnet-btc.tsx
src/global.d.ts
tsconfig.json
yarn.lock

As a user I want to get tBTC to test the bridge on the sbtc testnet env
resolves https://github.com/stacks-network/sbtc/issues/965

965 when the bridge is in testnet mode inform users on how to get regtest bitcoin

---

src/comps/ConnectWallet.tsx
src/comps/Deposit.tsx
src/comps/Header.tsx
src/comps/HomeApp.tsx
src/comps/alerts/info.tsx
src/comps/alerts/success.tsx
src/comps/deposit-stepper.tsx
src/hooks/use-notifications.ts
src/hooks/use-short-address.ts
src/util/WalletContext.tsx

Resolves https://github.com/stacks-network/sbtc/issues/974
Flow video:
https://github.com/user-attachments/assets/542b76ae-f2dc-4df0-9761-0bb07bb39ab9

Deposit status steps

---

src/actions/get-current-sbtc-supply.ts
src/util/get-aggregate-key.ts
src/util/get-stacks-network.ts

Use the following template to create your pull request
wallet network was passed as a stacks network which broke getting the current sbtc supply
- Bug fix

add helper function to get correct stacks network based wallet network

---

src/comps/Deposit.tsx

Use the following template to create your pull request
Sats internally and BTC externally
https://github.com/user-attachments/assets/46e3919b-65b6-4b6f-854d-80f867fd6f59

use sats internally and btc in UI

---

src/app/layout-client.tsx
src/app/layout.tsx
src/app/page.tsx
src/app/status/page.tsx
src/app/transfer/page.tsx
src/comps/Header.tsx
src/comps/ui/metrics.tsx
src/comps/ui/sbtc-balance.tsx
src/util/get-token-price.ts

Show the current TVL and circulating supply of sBTC as metrics of the system
For details refer to issue https://github.com/stacks-network/sbtc/issues/1025
- New feature
No
No

Chore/ tvl and sbtc circulating supply metrics

---

src/app/layout.tsx

Env vars are not loading this fixes it

fix env not loading correctly

---

src/comps/Deposit.tsx

fix amount placeholder to ask for BTC amounts instead of sats

---

src/actions/get-testnet-btc.ts
src/comps/get-testnet-btc.tsx

Now shows an error and asks user to try again if the faucet doesn't work, previously failed silently

Correctly display an error when the faucet doesn't work

---

src/app/globals.css
src/comps/Faqs.tsx

Add extra FAQs

---

src/app/api/proxy/[...proxy]/route.ts

- return responses like text (for tx lookup)

fix: return if okay

---

next.config.js
src/comps/ConnectWallet.tsx
src/comps/Notifications.tsx
src/util/wallet-utils/src/getAddress.ts

Leather ledger users weren't able to find a correct error message letting them know why they couldn't connect to the app this lets them know that they need to connect their bitcoin wallets on leather

Notify ledger users if they haven't connected their btc wallet

---

src/comps/Faqs.tsx

updated FAQs to latest

---

src/comps/ConnectWallet.tsx

If the user did not install a wallet of the two options they would be prompted to install it
Fixes:
- https://github.com/stacks-network/sbtc/issues/1146

show the users an install link if they have not installed a wallet

---

src/actions/get-btc-balance.ts
src/actions/get-emily-limits.ts
src/app/api/emilyDeposit/route.ts
src/comps/Deposit.tsx
src/comps/deposit-stepper.tsx
src/comps/ui/sbtc-balance.tsx
src/hooks/use-deposit-status.ts
src/hooks/use-mint-caps.ts

Fixes:
- https://github.com/stacks-network/sbtc/issues/1137
- https://github.com/stacks-network/sbtc/issues/1141

Add extra logs when sending a deposit and don't allow the user to exceed their balance

---

src/actions/bitcoinClient.ts
src/comps/ReclaimManager.tsx
src/hooks/use-deposit-status.ts
src/hooks/use-reclaim-status.ts

This checks if the deposit tx exists and if it doesn't it fetches if it has been rbf'ed and if so redirect to the rbf'ed tx after notifying emily

replace by fee handling for deposits

---

src/actions/bitcoinClient.ts
src/app/api/emilyDeposit/route.ts
src/comps/Deposit.tsx
src/util/use-emily-deposit.ts

make sure to fail the whole request and retry if tx not found yet

add transactionHex to parameters when notifying emily

---

package.json
src/comps/ConnectWallet.tsx
src/util/wallet-utils/src/checkWallets.ts
src/util/wallet-utils/src/getAddress.ts
src/util/wallet-utils/src/sign-psbt.ts
yarn.lock

Xverse broke their old getAddresses wallet and that breaks the whole stack this hotfix addresses that

fix xverse connect

---

src/util/wallet-utils/src/sign-psbt.ts

for dear @matteojug who noticed this bug with leather reclaims

fix psbts for leather

---

package.json
src/comps/ReclaimManager.tsx
yarn.lock

instead of one false we send two now

bump asigna to 0.0.25

---

src/app/layout-client.tsx
src/comps/footer.tsx

This would only work for public mainnet and testnet will not work locally as the explorer url is not deterministic (not in an ENV var)

fix footer contracts to change based on env

---

src/app/globals.css
src/app/layout-client.tsx
src/app/layout.tsx
src/app/old-layout-client.tsx
src/app/old-layout.tsx
src/app/page.tsx
src/app/reclaim/page.tsx
src/app/reskin/layout.tsx
src/app/reskin/page.tsx
src/app/status/page.tsx
src/app/transfer/page.tsx
src/app/withdraw/page.tsx
tailwind.config.ts

This separates the old bridge interface in root `/` and the reskin`/` which is now just text with no relation to the old bridge ui
https://github.com/user-attachments/assets/a9a657ea-c3bb-4945-b0fa-a08d60e9b72b

add hello world on an empty reskin page

---

src/app/reskin/components/header/connect-button.tsx
src/comps/tos.tsx

Show TOS after connect and refine TOS UI
https://github.com/user-attachments/assets/6158ff8c-d8e9-4e7b-9e83-41b7d56b9e59

fix add TOS after connect in reskin and update TOS ui

---

src/app/reskin/components/footer.tsx
src/app/reskin/components/header/header.tsx
src/app/reskin/history/page.tsx
src/app/reskin/layout-client-reskin.tsx
src/app/reskin/page.tsx
src/app/reskin/withdraw/page.tsx

use the nav for footer in mobile and use an informational footer in tablets and larger
https://github.com/user-attachments/assets/9826e97d-dd85-4a36-942f-04d0c62ec843

add initial footer

---

src/app/api/proxy/[...proxy]/route.ts
src/comps/temp-withdraw.tsx
src/env.ts
src/util/validate-bitcoin-address.ts

This would fix an issue @andrerserrano had when depositing

handle nested segwit address requests in proxy

---

src/comps/ConnectWallet.tsx

we don't know if p2pk or p2pkh would break stuff so let's stay safe

only support segwit addresses for mainnet

---

src/comps/core/FlowContainer.tsx

You might feel my frustration watching this video sorry for that lol
https://github.com/user-attachments/assets/e492e73b-1325-44d0-b11e-0473ebaec971

removed sidebar from deposits and withdrawal flows

---

package.json
src/util/wallet-utils/src/getAddress.ts
src/util/wallet-utils/src/util/asigna-provider.ts
yarn.lock

This only get the stacks address the rest of the implementation would only support withdrawals

Add ability to connect asigna stx multisig

---

Dockerfile

add feature flags as args to dockerfile

---

.env.sample
src/actions/get-withdrawal-max-fee.ts
src/app/withdraw/components/withdraw-amount.tsx
src/app/withdraw/components/withdraw-client.tsx
src/env.ts
src/util/constants.ts

fee rate for withdrawals in devenv is 60sats/vByte not sure if this is a bug?

use a dynamic max fee for withdrawals

---

src/actions/get-aggregate-key.ts
src/comps/Deposit.tsx

resolves https://github.com/stacks-network/sbtc/issues/1393

disable deposits if aggregate key is not available

---

package.json
src/app/withdraw/components/withdraw-client.tsx
src/util/wallet-utils/src/callContract.ts
yarn.lock

Asigna integration for withdrawals and that marks all supported wallets as integrated!

update @stacks/transactions and add asigna contract call

---

src/actions/get-emily-withdrawal.ts
src/app/layout-client.tsx
src/app/layout.tsx
src/util/depositRequest.ts

the problem was that ecc lib was not init globally the fix was to init ecc lib globally for both server and client components and remove local inits

fix aggregate key not showing in withdraw page

---

src/app/old-layout-client.tsx
src/app/old-layout.tsx
src/app/withdraw/[txid]/error.tsx
src/comps/footer.tsx
src/hooks/use-sbtc-balance.ts

This basically delays requesting the balance from the action until the ui is loaded, and for footer uses full SSR to make sure the env is passed accurately

fix sbtc balance not loading and footer aggregate address not working

---

next.config.js
src/app/old-layout-client.tsx
src/app/reskin/components/tabs/nav-tabs.tsx
src/app/reskin/layout-client-reskin.tsx
src/comps/Header.tsx

check this out
https://github.com/user-attachments/assets/47b50e08-5ad5-4891-8414-4e6e1e2b460d

cuter nav for bridge between deposit and withdraw

---

src/app/withdraw/components/withdraw-address.tsx
src/comps/Deposit.tsx
src/comps/core/Form.tsx

Adds a note for the prefilled address in both withdraw and deposit
Resolves: https://github.com/stacks-network/sbtc/issues/1545
https://github.com/user-attachments/assets/48ea769c-8323-4f89-8ddb-3421b48f7601

add notice to let the user know about the prefilled address

---

src/app/api/health/route.ts
src/env.ts

this reads from env to health endpoint

add commit id env var to health endpoint

---

src/app/withdraw/[txid]/components/withdrawal-status.tsx
src/app/withdraw/[txid]/page.tsx

Resolves: https://github.com/stacks-network/sbtc/issues/1551

use client fetch for withdrawal status

---

src/actions/get-emily-limits.ts
src/app/withdraw/components/util/validate-withdraw-amount.ts
src/app/withdraw/components/withdraw-client.tsx

Resolves https://github.com/stacks-sbtc/sbtc/issues/1544

add validation for available to withdraw param limit

---

src/app/reskin/[slug]/info.tsx
src/app/reskin/[slug]/reclaim/components/reclaim-stepper.tsx
src/app/reskin/[slug]/reclaim/components/stepper.tsx
src/app/reskin/[slug]/reclaim/hooks/useSubmitReclaim.ts
src/app/reskin/[slug]/reclaim/page.tsx
src/app/reskin/[slug]/reclaim/reclaim-client.tsx
src/app/reskin/[slug]/reclaim/reclaim-form.tsx
src/app/reskin/components/forms/form-elements/input-container.tsx
src/app/reskin/components/stepper/deposit/status.tsx
src/hooks/use-reclaim-status.ts
src/util/wallet-utils/src/sign-psbt.ts

Reclaims on reskin
https://github.com/user-attachments/assets/f5b78ea3-ab61-4fd4-9244-b679f5f5baa0

reskin reclaims

---

src/app/reskin/withdraw/[slug]/info.tsx
src/app/reskin/withdraw/[slug]/page.tsx
src/app/reskin/withdraw/[slug]/status-client.tsx
src/app/reskin/withdraw/components/form/address-input.tsx
src/app/reskin/withdraw/components/form/amount-input.tsx
src/app/reskin/withdraw/components/form/withdraw-form.tsx
src/app/reskin/withdraw/components/stepper.tsx
src/app/reskin/withdraw/components/withdraw-stepper.tsx
src/app/reskin/withdraw/hooks/use-submit-withdraw.ts
src/app/reskin/withdraw/hooks/use-withdrawal-info.ts
src/app/reskin/withdraw/hooks/withdrawal-validation.ts
src/app/reskin/withdraw/withdraw-client.tsx

Resolves https://github.com/stacks-sbtc/sbtc/issues/1603
https://github.com/user-attachments/assets/d33c2532-bea9-4ede-abf9-034fb43395e2

reskin withdrawals

---

package.json
src/app/reskin/components/forms/deposit/deposit-form.tsx
src/app/reskin/withdraw/hooks/use-submit-withdraw.ts
yarn.lock

0.0003 is one problematic number

fix floating point issues with js in both deposit and withdraw

---

src/app/_withdraw/components/util/validate-withdraw-amount.ts
src/hooks/use-validate-deposit-amount.ts

add validation for max decimal places in both deposits and withdrawals

---

src/app/(reskin)/withdraw/components/form/amount-input.tsx
src/app/(reskin)/withdraw/components/form/withdraw-form.tsx

https://github.com/user-attachments/assets/041c0ab4-4f1b-450f-9cc4-81ba94b92938

show connect wallet button wen wallet not connected in form

---

src/app/layout.tsx

Fix: https://github.com/stacks-sbtc/sbtc-bridge/issues/189
https://github.com/user-attachments/assets/f181fbf0-e79f-497c-b7d3-b4479670d64e

Sticky banner

---

src/comps/ConnectWallet.tsx
src/util/atoms.ts

Ticket: https://github.com/stacks-sbtc/sbtc-bridge/issues/175
https://github.com/user-attachments/assets/07f1f0cc-0a75-44fe-9c68-17d230f76c06

Show user agreement once for each address
